#override defaults for dev
version: "3.7"

services:
  app_server:
    build: .
    links:
      - mysql
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/sw6
      - APP_URL=http://localhost:8000
      - APP_SECRET=8583a6ff63c5894a3195331701749943
      - APP_ENV=prod
      - INSTANCE_ID=
      - SHOPWARE_ES_ENABLED=1
      - SHOPWARE_ES_HOSTS=elasticsearch:9200
      - SHOPWARE_ES_INDEXING_ENABLED=1
      - SHOPWARE_ES_INDEX_PREFIX=sw
      - SHOPWARE_HTTP_CACHE_ENABLED=1
      - SHOPWARE_HTTP_DEFAULT_TTL=7200
    volumes:
      - "./config/jwt:/sw6/config/jwt"
      - "./artifacts:/artifacts"
      #- "./public:/sw6/public"
      #- "./var:/sw6/var"
      #- "./bin:/sw6/bin"
      #- "./src:/sw6/src"
      #- "./vendor:/sw6/vendor"
      #- "./platform/src/Core:/sw6/vendor/shopware/core"
      #- "./platform/src/Administration:/sw6/vendor/shopware/administration"
      #- "./platform/src/Elasticsearch:/sw6/vendor/shopware/elasticsearch"
      #- "./platform/src/Recovery:/sw6/vendor/shopware/recovery"

  mysql:
    image: mysql:5.7
    tmpfs:
      - /var/lib/mysql:uid=999,gid=999
    environment:
      - MYSQL_ROOT_PASSWORD=root

  elasticsearch:
    image: elastic/elasticsearch:7.1.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
